### ISSUE TITLE
Workarounds for Android UMP

### ISSUE THREAD

**Issue by robinshin** [bocops/UMP-workarounds#1]
Hello,

First of all, thank you for this clear documentation: I searched a lot but didn't find any clear explanation why my Android users could not have any ads when not fully consenting Google UMP.

I wanted to ask if there were any existing workaround today instead of changing mediation platform?

**Comment by bocops** [comment]
@robinshin Thanks for your comment, I had hoped that this would be useful for someone. :)

As far as I can tell, there's no real workaround for the core problem. If the consent configured via UMP is lacking, no ads will be shown. Even manually overriding the stored consent (which shouldn't be done in a production app, because you'd be breaking GDPR or similar laws) does not work, because Google UMP seems to store a server-side hash of the given consent and the on-device information is considered invalid in case of a mismatch.

The only thing you _can_ do is to check the consent information stored on the device, and then configure your app (e.g. disable functionality as a sort of freemium model). This involves checking the stored strings for consent, legitimate interest and vendors against the minimum configuration that would lead to ads being shown. I can add something along those lines shortly.

**Comment by bocops** [comment]
@robinshin I now added a workaround to [check for insufficient consent](https://github.com/bocops/UMP-workarounds/tree/main/detect_insufficient_consent/android/kotlin).

Most of this was copied from working code, so should be OK, but I couldn't yet test some of the changes I made for readability. If you use this code, it would be great if you could let me know if everything works, or what needs to be changed.

**Comment by robinshin** [comment]
Hello!

Thanks a lot for your detailed answer!

For now, I will simply turn off GDPR message and only request non personalized ads for my android users waiting for a decent UMP solution from google ... Hoping that it will come soon
