### ISSUE TITLE
Question: possible to mimic ConsentInformation.canRequestAds, yet from cache?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bocops/UMP-workarounds#6]
Is there any way to use the exact same thing that `ConsentInformation.canRequestAds` does, yet read from cache if possible?
I thought that maybe `detectAdConfiguration` could do this by just checking that it's not "NONE".

**Comment by bocops** [comment]
UMP's `canRequestAds()` only

> indicates whether the app has completed the necessary steps for gathering updated user consent. ([link](https://developers.google.com/admob/android/privacy/api/reference/com/google/android/ump/ConsentInformation#public-abstract-boolean-canrequestads))

This means that it should return true after you've called `requestConsentInfoUpdate(...)`, but not before.

Essentially, this function of Google's UMP really just checks if the legal and/or technical prerequisites for **requesting** ads are given, but not whether there is sufficient user consent for ads to be **served** and **displayed** via AdMob.

There is no need to cache or read from cache anything here, because the function just checks whether all steps that are _mandatory_ anyway have been peformed.

**Comment by AndroidDeveloperLB** [comment]
But this is not good.
Calling requestConsentInfoUpdate takes some time compared to a cached result.
And after `canRequestAds` returns true, it should be fine to initialize ads, requesting and showing them.
Not much developers can do after consent was chosen, other than starting showing ads. You could use this repository to perhaps check how much the user has chosen, but still you should be able to start requesting ads.

Please tell how to check the cache for the result of `canRequestAds` of previous sessions, so that `requestConsentInfoUpdate` won't be needed in every session but only when the cached result doesn't exist.

**Comment by bocops** [comment]
> Please tell how to check the cache for the result of canRequestAds of previous sessions, so that requestConsentInfoUpdate won't be needed in every session but only when the cached result doesn't exist.

This is not possible until Google changes how their SDKs work!

**Comment by AndroidDeveloperLB** [comment]
How does it work? It works only based on current session's result from requestConsentInfoUpdate ?
No caching at all?
So how is this repository handling some cached results? Why the need to delete them if they are expired, if requestConsentInfoUpdate is being called anyway? Wouldn't requestConsentInfoUpdate replace the previous ones?

This seems worse than I thought... And confusing.

**Comment by bocops** [comment]
`requestConsentInfoUpdate()` checks if there's a valid consent status stored, including a complete opt out of all consent. This check _should_ include checking how old that consent status is, because user's should see the dialog roughly once a year - but due to a bug on Google's end, this just did not happen until recently.

The function in this repository deletes data if it is outdated, because having _no_ cached data to work on will force UMP to display the dialog again.

**Comment by AndroidDeveloperLB** [comment]
I mean "How does canRequestAds work" . 
I don't get it: If the data is stored already, why shouldn't it be possible to reach it instead of calling requestConsentInfoUpdate again and again (once per process start)....
And why does it even require Activity if it's not UI-based (only the dialog is, and even there we should have better ways...).

**Comment by bocops** [comment]
You are completely right, it _could_ work just like that. The reasons for why it doesn't may include some weird legal edge case, for example:

1. Cache states that no user consent is necessary (for example because a non-EU user is accessing the app outside the EU)
2. Ad is being displayed
3. Update consent status reveals that consent would have been necessary (for example because the device has moved into the EU region since last app startup)

Given that sequence, an ad would have been shown to (and some personal information about them transferred/stored) someone who hasn't opted in, although they have the legal right to be asked. That risk is likely minimal (and whatever checks they actually do might not be 100% bulletproof, either), but that's the way it is.

**Comment by AndroidDeveloperLB** [comment]
OK so what will happen in the next scenario:

- I let the user have the consent dialog. He chooses whatever. Let's assume accept all stuff there.
- The process dies
- Instead of requestConsentInfoUpdate, I use your function of detectAdConfiguration (after calling deleteTCStringIfOutdated , to make sure that it's still ok), and as I see it's not "None", I initialize ads and try to load&show them

?

1. Is it against the rules? 
2. Will this punish the app/developer in some way? 
3. Will it provide ads at all? 
4. I get limited/non-personalized ads? 
5. Admob will wait till a valid response from requestConsentInfoUpdate will be returned?
6. If requestConsentInfoUpdate is called later, will it get resolved automatically ? Admob listen to state-changes?


It's just that detectAdConfiguration  is much faster than requestConsentInfoUpdate and doesn't require Activity...

**Comment by bocops** [comment]
The original question is likely solved via the recently added function `getPreviousConsentStatus`.

I am neither a lawyer nor a Google employee, so I am not really able to answer most of the additional questions beyond reasonable guesses.

**Comment by AndroidDeveloperLB** [comment]
I don't live in a region that has the ad-consent, so I ask what would happen as I won't be able to know this easily at all. 

Do you think ad-providers and/or Admob just check the SharedPreferences as you have, and that's it?
Or they require that I really call the ad-consent SDK's function of requestConsentInfoUpdate , and till then nothing is acceptable and they will provide only "Limited ads" ? 

Or all is guesses for now...

**Comment by bocops** [comment]
Let's continue this in a discussion: #9
