### ISSUE TITLE
Question: Is there any way to get the cached result of `ConsentInformation.getPrivacyOptionsRequirementStatus` ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bocops/UMP-workarounds#7]
Is there any way to get the cached result of `ConsentInformation.getPrivacyOptionsRequirementStatus` as well? For some reason, despite the docs saying otherwise, it doesn't return the last value , so I still need to call `requestConsentInfoUpdate` to query this :
https://groups.google.com/g/google-admob-ads-sdk/c/CUL9BnJ0YU4

**Comment by bocops** [comment]
This status does not seem to be a part of the IABTCF specifications that UMP tries to implement, but something internal to UMP. For what it is worth, in my app implementing UMP, there's a file `__GOOGLE_FUNDING_CHOICE_SDK_INTERNAL__.xml` with a key `privacy_options_requirement_status` (and in my case value `REQUIRED`), so you should be able to do something like this:

```kotlin
fun getCachedPrivacyOptionsRequirementStatus(context: Context): String? {
    val sp = context.getSharedPreferences("__GOOGLE_FUNDING_CHOICE_SDK_INTERNAL__", Context.MODE_PRIVATE)
    return sp.getString("privacy_options_requirement_status", null)
}
```

However, I don't know if reading this cached result will help you, because there's no way to convince Google's UMP to rely on external data that you feed it. As such, I don't think this is something that should be added here, unless you can find a way for this to be actually put to use. :)

**Comment by AndroidDeveloperLB** [comment]
According to the docs, it should return it, but as I noticed it's a bug that it doesn't, I thought maybe it's just cached but not received.

What do you mean about "rely on external data that you feed it"? 
I need to get the cached result that the SDK has saved (and hopefully it gets updated in case it's expired, or something). 
As for "put to use", the point is to avoid using requestConsentInfoUpdate when the cached value already exists (as requestConsentInfoUpdate can sometimes take some time compared to just SharedPreferences check ).

**Comment by bocops** [comment]
You can't avoid calling `requestConsentInfoUpdate(...)`, though. According to [the documentation](https://developers.google.com/admob/android/privacy/api/reference/com/google/android/ump/ConsentInformation?hl=en)

> This API **must** be called in each app session before calling getConsentStatus().

If you do not call this function, you will not get access to the cached result (and AdMob potentially might not use it either, in which case no ads would be displayed):

> After this API is called, the getConsentStatus() API return value will be updated synchronously to hold the consent state from the previous app session, if one exists.

**Comment by AndroidDeveloperLB** [comment]
I didn't say that I won't call requestConsentInfoUpdate at all.
I said that if I have a cached result from previous session, I will use it instead of calling requestConsentInfoUpdate.
Shouldn't this be ok?
If the result is already cached (and yet I didn't call requestConsentInfoUpdate on the new session, meaning not even once ever since the process was created, but called it before), Admob should be able to access it, just like it's accessed here in this repository, no?

**Comment by bocops** [comment]
That's not how this works on Google's end, though. Yes, AdMob and/or UMP _should_ be able to access any information they previously stored in your app's context during a previous run - but if they simply don't, but instead rely on you to properly initialize their SDK's as they outlined in their documentation, then trying to get a cached result using out-of-band means might just mean that there is a discrepancy between what you as the developer believe to be the case ("there's cached consent, so ads will be shown") and what AdMob will act upon ("no sufficient setup, no ads").

For what it's worth, I completey agree with most criticism regarding UMP in general and its current, weird API, specifically - but that is something that we all need to take up with Google.

**Comment by AndroidDeveloperLB** [comment]
Wait, are you saying that on every session, even if you already had handled consent, even if the user has accepted everything or isn't even in a place that requires ad-consent, and even though all could be enough in the cache, it's not good to start initialization of ads and requesting ads?

If so, this means slow loading before showing ads.

Not only that, but it also mean that as long as the app doesn't have any Activity running yet, it can't initialize ads yet (because for some reason the most important functions require Activity) ...

**Comment by bocops** [comment]
> Wait, are you saying that on every session, even if you already had handled consent, even if the user has accepted everything or isn't even in a place that requires ad-consent, and even though all could be enough in the cache, it's not good to start initialization of ads and requesting ads?

Probably yes. I've seen anecdotes by developers claiming that doing both concurrently works for them, but that might just be a race condition resolved in the best-possible way.

What I am definitely saying is that any use of data cached locally by the developer should not _replace_ calls to initialize either of Google's SDKs the way they want it to be initialized, because that surely will cause issues down the line.

If you _want_ to cache anything in order to check whether concurrent initialization should even be attempted on the next start of your app, I can't really help you at the moment because this is not something I've tested yet. If I had to guess, though, I'd say that [`AdListener.onAdLoaded()`](https://developers.google.com/android/reference/com/google/android/gms/ads/AdListener#onAdLoaded()) could be a good place to do so. At that point, an ad will have been successfully loaded, so it might be reasonable to assume that it will continue to load for, say, the next week unless the given consent is already nearly outdated.

**Comment by AndroidDeveloperLB** [comment]
This is terrible. How come this whole mess has existed for so long (years?), and Google still doesn't offer an efficient, reliable way to query it?

**Comment by bocops** [comment]
Because they are run by lawyers and middle-of-the-road managers who are afraid to speak up and risk anything, and the same is true for individual employees that don't want to be a part of the next reduction in workforce. At the same time, their "Mobile Ads SDK" forum is for the most part likely managed by some outsourced call center, with agents sometimes even using LLMs to write their incoherent replies. :(

**Comment by AndroidDeveloperLB** [comment]
Is there no better solution?
I remember some people on reddit said that while there are alternatives to Google's SDK (and Google even mentions a list of them somewhere, yet hard to find), they cost money.

**Comment by bocops** [comment]
Between the suggestion above and the similar `getPreviousConsentStatus` that was recently added, the original question here seems resolved. I can't suggest any specific alternatives to Google's SDK.

**Comment by AndroidDeveloperLB** [comment]
Thank you for all the time
